version: '3'

services:
  jupyter:
    command: start-notebook.sh --NotebookApp.token=''
    image: jupyter/tensorflow-notebook
    ports:
      - "8888:8888"
    volumes:
      - ./work:/home/jovyan/work
